version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - java -version
      - mvn package
      
      
artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    artifact1:
      files:
      directory: 'fileupload_downloadapp'
      base-directory: 'target/Myproject'
    artifact2:
      files:
      directory: 'insurancewebex'
      base-directory: 'target/Myproject2'   
    artifact3:
      files:
      directory: 'springwebex'
      base-directory: 'target/Myproject3'
