version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - java -version
      - mvn package
      
      
artifacts:
  files:
    - '**/*'
  base-directory: 'fileupload_downloadapp/target/Myproject'
  
artifacts:
  files:
    - '**/*'
  base-directory: 'insurancewebex/target/Myproject2'
  
artifacts:
  files:
    - '**/*'
  base-directory: 'springwebex/target/Myproject3'
