version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - java -version
      - mvn package
      
      
      
      
 artifacts:
  files:
    - '**/*'
 artifact1:
   files:
    - '**/*'
   base-directory: 'fileupload_downloadapp/target/Myproject'
 artifact2:
   files:
    - '**/*'
   base-directory: 'insurancewebex/target/Myproject2'
 artifact3:
   files:
    - '**/*'
   base-directory: 'springwebex/target/Myproject3'
 
 
 
  
  
  
  
