version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - java -version
      - mvn package
      
      
      
      
 artifacts:
  files:
    - '**/*'
  secondary-artifacts:
    artifact1:
      files:
        - 'fileupload_downloadapp/target/Myproject'
      name: fileupload_downloadapp
    artifact2:
      files:
        - 'insurancewebex/target/Myproject2'
      name: insurancewebex
    artifact3:
      files:
        - 'springwebex/target/Myproject3'
      name: springwebex
 
 
 
  
  
  
  
